
import Head from 'next/head'
import Header from "../components/header"
import Banner from "../components/banner"
import Corpo from "../components/corpo"
import { Inter } from 'next/font/google'
import Rodape from '../components/rodape'
import Contato from '../components/contato'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{position:"fixed", zIndex:1,width:"100%"}}><Header/></div>
      <Banner/>
      <Corpo/>
      <Contato/>
      <Rodape/>
    </>
  )
}
